apiVersion: v1 # versão da API
kind: ConfigMap # tipo de recurso, no caso, um ConfigMap
metadata: # metadados do recurso
  name: nginx-config # nome do recurso
data: # dados do recurso
  nginx.conf: | # inicio da definição do arquivo de configuração do Nginx
    server {
      listen 80;
      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }
      location /metrics {
        stub_status on;
        access_log off;
      }
    }
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Minha Página Simples</title>
      <link rel="stylesheet" href="style.css">
    </head>
    <body>
      <header>
        <h1>Bem-vindo à Minha Página!</h1>
      </header>
      <main>
        <p>Esta é uma página HTML básica com estilo aplicado por CSS.</p>
        <button>Saiba Mais</button>
      </main>
      <footer>
        <p>&copy; 2024 - Minha Página Simples</p>
      </footer>
    </body>
    </html>
  style.css: |
    /* Estilo geral */
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      background-color: #f0f0f0;
      color: #333;
      text-align: center;
    }

    /* Cabeçalho */
    header {
      background-color: #4CAF50;
      color: white;
      padding: 1rem 0;
    }

    header h1 {
      margin: 0;
    }

    /* Conteúdo principal */
    main {
      padding: 2rem;
    }

    main p {
      font-size: 1.2rem;
      margin: 1rem 0;
    }

    main button {
      background-color: #4CAF50;
      color: white;
      border: none;
      padding: 0.5rem 1rem;
      font-size: 1rem;
      cursor: pointer;
      border-radius: 5px;
    }

    main button:hover {
      background-color: #45a049;
    }

    /* Rodapé */
    footer {
      background-color: #333;
      color: white;
      padding: 1rem 0;
      margin-top: 2rem;
    }